name: manually

on:
  workflow_dispatch:
    inputs:
      city:
        description: '广东省市? 默认省，如珠海'
        required: true
        default: ''
        
jobs:
  classify:
    runs-on: ubuntu-latest
    steps:
    - name: pull
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@master
      with:
       python-version: '3.10'
    - name: preload env
      #shell: cmd
      run: pip install -r requirements.txt
    - name: download
      run: python info_GDTZ.py get_class "${{github.event.inputs.city}}"
    - name : Upload
      uses: actions/upload-artifact@master
      with:
        name: out
        path: "${{github.event.inputs.class}}.xlsx"
    - name: Commit files
      run: |
        git config --local user.email "goonhope@gmail.com"
        git config --local user.name "goonhope"
        git add -A
        git commit -m "Update `date -d '8 hour' '+%Y/%m/%d %H:%M:%S'`" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.PASS }}
        branch: main 
