name: manually
on:
  workflow_dispatch:  
  schedule:
    - cron: "30 4 * * 1-5"
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
       - name: check
         uses: actions/checkout@master
       - name: setup env
         uses: actions/setup-node@v4
         with:
           node-version: '20'
       - name: test
         run: |
           npm install npm node-fetch
           node index.js > list.csv
       - name : Upload artifact
         uses: actions/upload-artifact@master
         with:
          name: list
          path: list.csv
           
